#!/usr/bin/env bash
# backup.sh — Smart OpenClaw disaster recovery backup
# 
# Usage:
#   ./backup.sh [--cron] [--dry-run] [--upload-google-drive]
#   ./backup.sh --restore /path/to/backup.tar.gz
#
# Rules are loaded from backup-rules.json in the workspace directory

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -f "${REPO_DIR}/.env.backup" ]]; then
  # shellcheck disable=SC1091
  source "${REPO_DIR}/.env.backup"
fi

WORKSPACE="/root/openclaw-stock-home/.openclaw/workspace"
RULES_FILE="${WORKSPACE}/backup-rules.json"
BACKUP_DIR="/root/openclaw-stock-home/.openclaw/backups"
LOG_FILE="${BACKUP_DIR}/backup.log"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
BACKUP_FILE="openclaw-disaster-recovery-${TIMESTAMP}.tar.gz"
MANIFEST_FILE="${BACKUP_DIR}/openclaw-disaster-recovery-${TIMESTAMP}.manifest.json"

# Parse arguments
DRY_RUN=false
UPLOAD_GDRIVE=false
RESTORE_FILE=""
CRON_MODE=false

while [[ $# -gt 0 ]]; do
  case $1 in
    --dry-run)
      DRY_RUN=true
      shift
      ;;
    --upload-google-drive)
      UPLOAD_GDRIVE=true
      shift
      ;;
    --cron)
      CRON_MODE=true
      shift
      ;;
    --restore)
      RESTORE_FILE="$2"
      shift 2
      ;;
    *)
      shift
      ;;
  esac
done

# Create backup directory if needed
mkdir -p "${BACKUP_DIR}"
mkdir -p "${BACKUP_DIR}/.history"

log() {
  local msg="[$(date '+%Y-%m-%d %H:%M:%S')] $*"
  echo "$msg" | tee -a "${LOG_FILE}"
}

# Load backup rules
if [[ ! -f "${RULES_FILE}" ]]; then
  log "ERROR: backup-rules.json not found at ${RULES_FILE}"
  exit 1
fi

log "Loading backup rules from ${RULES_FILE}"

# Extract rules using jq
EXCLUSIONS=$(jq -r '.exclusions[].pattern // empty' "${RULES_FILE}")
INCLUSIONS=$(jq -r '.inclusions[].pattern // empty' "${RULES_FILE}")

# Create temp files for tar exclusion/inclusion
EXCLUDE_FILE=$(mktemp)
INCLUDE_FILE=$(mktemp)

# Write exclusion patterns
echo "# Generated by backup.sh on ${TIMESTAMP}" > "${EXCLUDE_FILE}"
jq -r '.exclusions[] | "!" + .pattern' "${RULES_FILE}" >> "${EXCLUDE_FILE}"

# Write inclusion patterns  
echo "# Generated by backup.sh on ${TIMESTAMP}" > "${INCLUDE_FILE}"
jq -r '.inclusions[] | .pattern' "${RULES_FILE}" >> "${INCLUDE_FILE}"

# Create manifest
log "Creating backup manifest..."

cat > "${MANIFEST_FILE}" << EOF
{
  "version": "1.0.0",
  "timestamp": "${TIMESTAMP}",
  "backupFile": "${BACKUP_FILE}",
  "rulesFile": "${RULES_FILE}",
  "rulesVersion": "$(jq -r '.version // "unknown"' "${RULES_FILE}")",
  "excludedCount": $(jq '.exclusions | length' "${RULES_FILE}"),
  "includedCount": $(jq '.inclusions | length' "${RULES_FILE}"),
  "exclusions": [
EOF

jq -r '.exclusions[] | "    {\"pattern\": \"\(.pattern)\", \"reason\": \"\(.reason)\"}"' "${RULES_FILE}" | \
  awk 'NR>1{print ","} {print}' >> "${MANIFEST_FILE}"

cat >> "${MANIFEST_FILE}" << EOF
  ],
  "inclusions": [
EOF

jq -r '.inclusions[] | "    {\"pattern\": \"\(.pattern)\", \"reason\": \"\(.reason)\"}"' "${RULES_FILE}" | \
  awk 'NR>1{print ","} {print}' >> "${MANIFEST_FILE}"

cat >> "${MANIFEST_FILE}" << EOF
  ]
}
EOF

# Dry run mode
if [[ "${DRY_RUN}" == "true" ]]; then
  log "DRY RUN MODE - Would create backup: ${BACKUP_DIR}/${BACKUP_FILE}"
  log "Excluded patterns:"
  jq -r '.exclusions[] | "  - \(.pattern) [\(.reason)]"' "${RULES_FILE}"
  log "Included patterns:"
  jq -r '.inclusions[] | "  - \(.pattern) [\(.reason)]"' "${RULES_FILE}"
  log "Manifest: ${MANIFEST_FILE}"
  rm -f "${EXCLUDE_FILE}" "${INCLUDE_FILE}"
  exit 0
fi

# Build tar command
log "Creating backup archive..."

# Build exclude arguments
EXCLUDE_ARGS=""
while IFS= read -r pattern; do
  [[ -n "$pattern" ]] && EXCLUDE_ARGS="${EXCLUDE_ARGS} --exclude='${pattern}'"
done <<< "${EXCLUSIONS}"

# Build include arguments
INCLUDE_ARGS=""
while IFS= read -r pattern; do
  [[ -n "$pattern" ]] && INCLUDE_ARGS="${INCLUDE_ARGS} --include='${pattern}'"
done <<< "${INCLUSIONS}"

# Check if tar supports --transform (GNU tar)
if tar --version | grep -q GNU; then
  TAR_CMD="tar"
else
  log "WARNING: Using BSD tar - some features may be limited"
  TAR_CMD="tar"
fi

# Create backup (excluding tmp, then including specific patterns)
# This is a simplified approach - we backup the whole workspace but exclude patterns
cd "${WORKSPACE}/.."

BACKUP_PATH="${BACKUP_DIR}/${BACKUP_FILE}"

# Create tar with exclusions
if [[ "${CRON_MODE}" == "true" ]]; then
  # Silent mode for cron
  tar --create \
    --gzip \
    --file="${BACKUP_PATH}" \
    --exclude='node_modules' \
    --exclude='.git' \
    --exclude='.playwright-mcp' \
    --exclude='build' \
    --exclude='dist' \
    --exclude='tmp' \
    --exclude='venv' \
    --exclude='test-results' \
    --exclude='playwright-report' \
    --exclude='coverage' \
    --exclude='*.log' \
    --exclude='.DS_Store' \
    --exclude='logs/audit-*.log' \
    --exclude='public/opencv*.js' \
    --exclude='public/test*.html' \
    --exclude='public/testimg' \
    --exclude='public/*.map' \
    --exclude='public/*.json' \
    --exclude='.env*.local*' \
    workspace openclaw.json skills scripts 2>/dev/null || true
else
  # Verbose mode for interactive
  tar --create \
    --gzip \
    --file="${BACKUP_PATH}" \
    --exclude='node_modules' \
    --exclude='.git' \
    --exclude='.playwright-mcp' \
    --exclude='build' \
    --exclude='dist' \
    --exclude='tmp' \
    --exclude='venv' \
    --exclude='test-results' \
    --exclude='playwright-report' \
    --exclude='coverage' \
    --exclude='*.log' \
    --exclude='.DS_Store' \
    --exclude='logs/audit-*.log' \
    --exclude='public/opencv*.js' \
    --exclude='public/test*.html' \
    --exclude='public/testimg' \
    --exclude='public/*.map' \
    --exclude='public/*.json' \
    --exclude='.env*.local*' \
    workspace openclaw.json skills scripts 2>&1 | tee -a "${LOG_FILE}"
fi

# Verify backup
if [[ -f "${BACKUP_PATH}" ]]; then
  BACKUP_SIZE=$(stat -f%z "${BACKUP_PATH}" 2>/dev/null || stat -c%s "${BACKUP_PATH}" 2>/dev/null || echo "unknown")
  log "Backup created: ${BACKUP_FILE} (${BACKUP_SIZE} bytes)"
else
  log "ERROR: Backup file not created"
  exit 1
fi

# Create symlink to latest backup
ln -sf "${BACKUP_FILE}" "${BACKUP_DIR}/latest.tar.gz"
log "Created symlink: latest.tar.gz -> ${BACKUP_FILE}"

# Copy manifest to backup dir (already in correct location)
log "Manifest saved: $(basename "${MANIFEST_FILE}")"

# Upload to Google Drive if requested
if [[ "${UPLOAD_GDRIVE}" == "true" ]]; then
  log "Uploading to Google Drive..."
  
  # Get parent folder ID from rules or use default
  PARENT_ID=$(jq -r '.parentId // "1b9uskrej-gjGVG-RmeaSYdPk0deUOa3R"' "${RULES_FILE}" 2>/dev/null || echo "1b9uskrej-gjGVG-RmeaSYdPk0deUOa3R")
  
  # Check if gog CLI is available
  if command -v gog &> /dev/null; then
    # Export GOG_KEYRING_PASSWORD for non-interactive auth
    if [[ -z "${GOG_KEYRING_PASSWORD:-}" ]]; then
      log "WARNING: GOG_KEYRING_PASSWORD not set; skipping Google Drive upload"
      log "Run setup.sh to configure non-interactive auth"
    elif [[ -z "${GOG_ACCOUNT:-}" ]]; then
      log "WARNING: GOG_ACCOUNT not set; skipping Google Drive upload"
      log "Run setup.sh to configure account"
    else
      # Upload backup using gog CLI
      log "Uploading backup file using gog CLI..."
      if gog --account "${GOG_ACCOUNT}" drive upload "${BACKUP_PATH}" --parent "${PARENT_ID}" --name "${BACKUP_FILE}" 2>&1 | tee -a "${LOG_FILE}"; then
      log "Backup file uploaded successfully"
    else
      log "WARNING: Google Drive upload of backup failed"
    fi
    
      # Upload manifest
      log "Uploading manifest file using gog CLI..."
      MANIFEST_BASENAME=$(basename "${MANIFEST_FILE}")
      if gog --account "${GOG_ACCOUNT}" drive upload "${MANIFEST_FILE}" --parent "${PARENT_ID}" --name "${MANIFEST_BASENAME}" 2>&1 | tee -a "${LOG_FILE}"; then
        log "Manifest file uploaded successfully"
      else
        log "WARNING: Google Drive upload of manifest failed"
      fi
    fi
  else
    log "WARNING: gog CLI not found, skipping Google Drive upload"
    log "To enable Google Drive uploads, ensure gog CLI is installed"
  fi
  
  log "Google Drive upload complete"
fi

# Clean up old backups if in cron mode
if [[ "${CRON_MODE}" == "true" ]]; then
  log "Cleaning up old backups..."
  
  MAX_BACKUPS=$(jq -r '.retention.maxBackups // 30' "${RULES_FILE}")
  MIN_AGE_DAYS=$(jq -r '.retention.minAgeDays // 7' "${RULES_FILE}")
  
  # Keep latest and backups younger than minAgeDays
  ls -t "${BACKUP_DIR}"/openclaw-disaster-recovery-*.tar.gz 2>/dev/null | tail -n +$((MAX_BACKUPS + 1)) | while read -r old_backup; do
    if [[ -f "${old_backup}" ]]; then
      backup_age=$(find "${old_backup}" -mtime +${MIN_AGE_DAYS} -print 2>/dev/null | wc -l)
      if [[ "${backup_age}" -gt 0 ]]; then
        log "Removing old backup: $(basename "${old_backup}")"
        rm -f "${old_backup}"
      fi
    fi
  done
  
  log "Cleanup complete"
fi

# Post-backup commands
log "Running post-backup commands..."
while IFS= read -r cmd; do
  [[ -n "$cmd" ]] && eval "$cmd" >> "${LOG_FILE}" 2>&1
done < <(jq -r '.postBackupCommands[]? // empty' "${RULES_FILE}")

# Clean up temp files
rm -f "${EXCLUDE_FILE}" "${INCLUDE_FILE}"

log "Backup completed successfully!"
